In [39]:
import pandas as pd
df = pd.read_csv('../Decision Tree/Exercise/titanic.csv') #no need to redownload

In [40]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [41]:
df.drop(['PassengerId','Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis=1, inplace=True)

In [42]:
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [43]:
target = df.Survived
inputs = df.drop('Survived', axis=1)
inputs.head()

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [44]:
dummies = pd.get_dummies(inputs)
dummies.head()

   Pclass   Age     Fare  Sex_female  Sex_male
0       3  22.0   7.2500       False      True
1       1  38.0  71.2833        True     False
2       3  26.0   7.9250        True     False
3       1  35.0  53.1000        True     False
4       3  35.0   8.0500       False      True

In [45]:
inputs = pd.concat([dummies], axis=1)
inputs.head()

   Pclass   Age     Fare  Sex_female  Sex_male
0       3  22.0   7.2500       False      True
1       1  38.0  71.2833        True     False
2       3  26.0   7.9250        True     False
3       1  35.0  53.1000        True     False
4       3  35.0   8.0500       False      True

In [46]:
inputs.columns[inputs.isna().any()]
inputs.head(20)

    Pclass   Age     Fare  Sex_female  Sex_male
0        3  22.0   7.2500       False      True
1        1  38.0  71.2833        True     False
2        3  26.0   7.9250        True     False
3        1  35.0  53.1000        True     False
4        3  35.0   8.0500       False      True
5        3   NaN   8.4583       False      True
6        1  54.0  51.8625       False      True
7        3   2.0  21.0750       False      True
8        3  27.0  11.1333        True     False
9        2  14.0  30.0708        True     False
10       3   4.0  16.7000        True     False
11       1  58.0  26.5500        True     False
12       3  20.0   8.0500       False      True
13       3  39.0  31.2750       False      True
14       3  14.0   7.8542        True     False
15       2  55.0  16.0000        True     False
16       3   2.0  29.1250       False      True
17       2   NaN  13.0000       False      True
18       3  31.0  18.0000        True     False
19       3   NaN   7.2250        True     False

In [47]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(20)

    Pclass        Age     Fare  Sex_female  Sex_male
0        3  22.000000   7.2500       False      True
1        1  38.000000  71.2833        True     False
2        3  26.000000   7.9250        True     False
3        1  35.000000  53.1000        True     False
4        3  35.000000   8.0500       False      True
5        3  29.699118   8.4583       False      True
6        1  54.000000  51.8625       False      True
7        3   2.000000  21.0750       False      True
8        3  27.000000  11.1333        True     False
9        2  14.000000  30.0708        True     False
10       3   4.000000  16.7000        True     False
11       1  58.000000  26.5500        True     False
12       3  20.000000   8.0500       False      True
13       3  39.000000  31.2750       False      True
14       3  14.000000   7.8542        True     False
15       2  55.000000  16.0000        True     False
16       3   2.000000  29.1250       False      True
17       2  29.699118  13.0000       False      True
18       3  31.000000  18.0000        True     False
19       3  29.699118   7.2250        True     False

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)

In [60]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

model.fit(X_train, y_train)

GaussianNB()

In [61]:
model.score(X_test, y_test)

0.8100558659217877

In [62]:
y_test[:10]

602    0
679    1
669    1
50     0
575    0
779    1
816    0
695    0
419    0
62     0
Name: Survived, dtype: int64

In [63]:
model.predict(X_test[:10])

array([0, 1, 1, 0, 0, 1, 1, 0, 1, 0])